// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_FIREBASE_WEB_API_KEY',
    appId: '1:1018191232724:web:bb03bcecebfbf999554541',
    messagingSenderId: '1018191232724',
    projectId: 'gdsc360b',
    authDomain: 'gdsc360b.firebaseapp.com',
    storageBucket: 'gdsc360b.appspot.com',
    measurementId: 'G-CK9PE5FWBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_FIREBASE_ANDROID_API_KEY',
    appId: '1:1018191232724:android:b083a2cc339df1a7554541',
    messagingSenderId: '1018191232724',
    projectId: 'gdsc360b',
    storageBucket: 'gdsc360b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_FIREBASE_IOS_API_KEY',
    appId: '1:1018191232724:ios:25f5903a90b27ba0554541',
    messagingSenderId: '1018191232724',
    projectId: 'gdsc360b',
    storageBucket: 'gdsc360b.appspot.com',
    iosBundleId: 'com.example.gdsc360',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_FIREBASE_IOS_API_KEY',
    appId: '1:1018191232724:ios:c3bb1cc555dc54ea554541',
    messagingSenderId: '1018191232724',
    projectId: 'gdsc360b',
    storageBucket: 'gdsc360b.appspot.com',
    iosBundleId: 'com.example.gdsc360.RunnerTests',
  );
}
